all: output

output: errexit.c passivesock.c passiveTCP.c tcpclient.c connectsock.c connectTCP.c
	gcc -Wall -Wextra errexit.c passivesock.c passiveTCP.c tcpclient.c connectsock.c connectTCP.c -o output

clean: 
	rm output

